export default Object.freeze({
    SET_SINGLE_TASK: "SET_SINGLE_TASK",
    SET_OR_REMOVE_SPINNER: "SET_OR_REMOVE_SPINNER",
    SET_OR_REMOVE_MODAL: "SET_OR_REMOVE_MODAL",
    TOGGLE_MODAL: "TOGGLE_MODAL",
});