export default Object.freeze({
    SET_SINGLE_TASK: "SET_SINGLE_TASK",
    SET_OR_REMOVE_MODAL: "SET_OR_REMOVE_MODAL",
    TOGGLE_MODAL: "TOGGLE_MODAL",
    //ToDo
    SET_TASKS:"SET_TASKS",
    EDIT_TASK: "EDIT_TASK",
    ADD_TASK: "ADD_TASK",
    SET_OR_REMOVE_ADD_MODAL: "SET_OR_REMOVE_ADD_MODAL",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    DELETE_CHECKED_TASKS:"DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL:"TOGGLE_CHECK_ALL",
    CHECKED_TASKS:"CHECKED_TASKS",
    DELETE_TASK_MODAL:"DELETE_TASK_MODAL",
    TOGGLE_SET_EDITABLE_TASK:"TOGGLE_SET_EDITABLE_TASK",
    RESET_DADA:"RESET_DADA",
    //conatctForm
    HANDLE_CHANGE:"HANDLE_CHANGE",
    ERROR_MESSAGE:"ERROR_MESSAGE",
   
    RESET_FORM:"RESET_FORM",
    //Global
    SUBMIT_CONTACT:"SUBMIT_CONTACT",
    SUCCESS_MESSAGE:"SUCCESS_MESSAGE",
    SET_OR_REMOVE_SPINNER: "SET_OR_REMOVE_SPINNER",
    //TASK MODAL
    CHANGE_MODAL:"CHANGE_MODAL",
    SET_DATA:"SET_DATA",
});