export default Object.freeze({
    SET_SINGLE_TASK: "SET_SINGLE_TASK",
    SET_OR_REMOVE_SPINNER: "SET_OR_REMOVE_SPINNER",
    SET_OR_REMOVE_MODAL: "SET_OR_REMOVE_MODAL",
    TOGGLE_MODAL: "TOGGLE_MODAL",
    
    TOGGLE_OPEN_ADD_TASK_MODAL: "TOGGLE_OPEN_ADD_TASK_MODAL",
    ADD_TASK: "ADD_TASK",
    TOGGLE_CONFIRM_MODAL: "TOGGLE_CONFIRM_MODAL",
    TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL: "TOGGLE_CHECK_ALL"
});